### ISSUE TITLE
Try passchk_fast as password strength indicator

### ISSUE THREAD

**Issue by PeterTheOne** [whawty/auth#1]
https://github.com/sc0ttyd/passchk_fast

**Comment by equinox0815** [comment]
hmmm... i'm beginning to think that all thos strength indicators are stupid..

just try 'aaaaaaaaaaaaaa'  at http://scott.donnel.ly/passchk_fast-a-javascript-password-strength-utility-based-on-passchk/ -> this leads to a 'strong' password. 

probably it would be better to do this on the server side....

**Comment by equinox0815** [comment]
we should also consider this:

http://ux.stackexchange.com/questions/55645/does-a-password-strength-indicator-increase-password-strength

**Comment by equinox0815** [comment]
https://github.com/dropbox/zxcvbn

looks promising

**Comment by equinox0815** [comment]
fixed in 5ae1b12
