### ISSUE TITLE
changing the user password should trigger an update in the browser password store.

### ISSUE THREAD

**Issue by equinox0815** [whawty/auth#7]
When a user changes his/her password using the WebUI the browser should recognise this and ask the user to also update the entry in the password store of the browser. At the moment this does not work.

**Comment by PeterTheOne** [comment]
These links might help:
- http://stackoverflow.com/questions/2398763/how-does-browser-know-when-to-prompt-user-to-save-password
- http://stackoverflow.com/questions/2382329/how-can-i-get-browser-to-prompt-to-save-password

**Comment by equinox0815** [comment]
For Firefox this is fixed in 068ecf4.

Chrome and Opera still don't work. They trigger the prompt only if the form submit succeeds but since this is a single page HTML5 app we don't have a submit action...

**Comment by PeterTheOne** [comment]
try `<button type="submit" ...` instead of `<button type="button" ...`. Also try to `return false;` instead of using `event.preventDefault();`.

**Comment by equinox0815** [comment]
Thanks for the Tip @PeterTheOne. Unfortunately all the relevant buttons already have been `type="submit"`. I changed all the `event.preventDefault();` with `return false;` (7a6bb25) but Chrome and Opera still ignore it...

**Comment by equinox0815** [comment]
@PeterTheOne said: http://stackoverflow.com/questions/15462991

**Comment by equinox0815** [comment]
Thanks @PeterTheOne, it partly works now with change f56e3a3. Chrome/Chromium/Opera now ask to store the password on login. However they don't ask to replace it when i change the password using the 'change password' dialog.

But i'm afraid that's as good as it gets on these browsers. When i for example don't store the password at login and then change the password using the dialog the browser asks me if i want to store the password. This however only works if i reload the page after login and then open the dialog. 
It looks as if the browser only stores new passwords for sites where there is no password set. It won't update existing entries nor will it add another account to the store (as Firefox does). Also the browser seems to remember that i clicked not to store the password until the page is reloaded. Therefore it doesn't ask me again when i do the following:

login -> store password? = no -> open change password dialog -> edit new password and click 'Change'

But it will ask me if i do the following:

login -> store password? = no -> reload -> open change password dialog -> edit new password and click 'Change'

**Comment by PeterTheOne** [comment]
I did some testing:

chrome:
login -> save pw? -> save -> logout -> autofill -> login -> works
login -> save pw? -> never -> logout -> no autofill
login -> save pw? -> save -> change -> update pw? -> yes -> logout -> autofill wrong!?? -> refresh -> works!

firefox:
login -> save pw? -> save -> logout -> autofill -> login -> works
login -> save pw? -> not now -> logout -> no autofill
login -> save pw? -> save -> change -> update pw? -> yes -> logout -> autofill works!

**Comment by PeterTheOne** [comment]
Somehow I can't add users.. page refreshes, nothing else happens.

**Comment by equinox0815** [comment]
@PeterTheOne try running the app with 

`WHAWTY_AUTH_DEBUG=1 ./whawty-auth ...args...`

What is the output when you add a user? Can you add a user using the command line?

`WHAWTY_AUTH_DEBUG=1 ./whawty-auth add <username>`

**Comment by PeterTheOne** [comment]
Adding via commandline works, seems to be a js thing.

**Comment by equinox0815** [comment]
Todays changes by @PeterTheOne fixed the issue for firefox and improved things a lot for chrome/chromium so closing this for now.
